import type { Locale } from "@/lib/i18n/dictionaries";
import {
  defaultRandomListColor,
  sanitizeRandomListItems,
  type RandomListItem,
} from "@/lib/random-list/engine";

type StarterRandomListPreset = {
  id: string;
  name: string;
  items: string[];
};

const palette = [
  "#ef4444",
  "#f97316",
  "#f59e0b",
  "#84cc16",
  "#22c55e",
  "#14b8a6",
  "#06b6d4",
  "#3b82f6",
  "#6366f1",
  "#8b5cf6",
  "#d946ef",
  "#ec4899",
];

const wheelStarterPresets: Record<Locale, StarterRandomListPreset[]> = {
  en: [
    {
      id: "who-goes-first",
      name: "Who goes first",
      items: ["Me", "Left", "Right", "Across", "Newest arrival", "Last winner"],
    },
    {
      id: "cheers-with-who",
      name: "Cheers with who",
      items: ["Left", "Right", "Across", "Whole table", "Oldest friend", "Newest friend"],
    },
    {
      id: "truth-or-dare-mode",
      name: "Truth or Dare mode",
      items: ["Truth", "Dare", "Tell a story", "Table vote", "Pass it on", "Safe pass"],
    },
    {
      id: "table-dares",
      name: "Table dares",
      items: [
        "Compliment the person on your left",
        "Let the table write your caption",
        "Take a group selfie",
        "Imitate a friend for 5 seconds",
        "Rename someone at the table",
        "Sing one chorus",
        "Tell a tiny embarrassing story",
        "Speak in a dramatic voice",
      ],
    },
    {
      id: "quick-table-games",
      name: "Quick table games",
      items: [
        "Count without saying 7",
        "Continue the song",
        "Forbidden word",
        "Most likely to",
        "Never have I ever",
        "Two truths and a lie",
        "Would you rather",
        "Table vote",
      ],
    },
    {
      id: "light-penalties",
      name: "Light penalties",
      items: [
        "Drink water",
        "Eat a snack",
        "Post a harmless story",
        "Dance for 5 seconds",
        "Let the table pick your emoji",
        "Say sorry to the table",
        "Change seats",
        "No phone for one round",
      ],
    },
    {
      id: "next-song",
      name: "Next song",
      items: ["Thai pop", "Old-school Thai", "Dance", "Heartbreak", "90s/2000s", "International", "Live request", "Table pick"],
    },
    {
      id: "gossip-topic",
      name: "Story topic",
      items: ["Old crush", "Old trip", "Work story", "School story", "Bad date", "Family-safe secret", "Tonight's outfit", "Best comeback"],
    },
    {
      id: "order-more",
      name: "Order more",
      items: ["Fried snack", "Spicy salad", "Grilled item", "Rice dish", "Ice", "Mixer", "Soft drink", "Ask the table"],
    },
    {
      id: "table-job",
      name: "Table job",
      items: ["Call staff", "Order food", "Split the bill", "Pick music", "Take photo", "Check map", "Get ice", "Choose next place"],
    },
  ],
  th: [
    {
      id: "who-goes-first",
      name: "ใครโดนก่อน",
      items: ["เราเอง", "คนซ้าย", "คนขวา", "คนตรงข้าม", "คนมาช้าสุด", "คนชนะรอบก่อน"],
    },
    {
      id: "cheers-with-who",
      name: "ชนแก้วกับใคร",
      items: ["คนซ้าย", "คนขวา", "คนตรงข้าม", "ทั้งโต๊ะ", "เพื่อนเก่าสุด", "เพื่อนใหม่สุด"],
    },
    {
      id: "truth-or-dare-mode",
      name: "หมวด Truth or Dare",
      items: ["Truth", "Dare", "เล่าเรื่อง", "โหวตทั้งโต๊ะ", "ส่งต่อ", "ขอผ่าน"],
    },
    {
      id: "table-dares",
      name: "ภารกิจฮา ๆ",
      items: [
        "ชมคนซ้าย 1 ประโยค",
        "ให้ทั้งโต๊ะตั้งแคปชั่น",
        "ถ่ายรูปหมู่ตอนนี้",
        "เลียนแบบเพื่อน 5 วิ",
        "ตั้งฉายาให้คนในโต๊ะ",
        "ร้องท่อนฮุก 1 ท่อน",
        "เล่าเรื่องหน้าแตกสั้น ๆ",
        "พูดเสียงละคร 1 รอบ",
      ],
    },
    {
      id: "quick-table-games",
      name: "เกมเร็วในโต๊ะ",
      items: [
        "นับเลขห้ามพูด 7",
        "ต่อเพลง",
        "คำต้องห้าม",
        "ใครน่าจะที่สุด",
        "เคยหรือไม่",
        "สองจริงหนึ่งโกหก",
        "เลือกแบบไหนดี",
        "โหวตทั้งโต๊ะ",
      ],
    },
    {
      id: "light-penalties",
      name: "บทลงโทษเบา ๆ",
      items: [
        "ดื่มน้ำเปล่า",
        "กินกับแกล้ม",
        "ลงสตอรี่แบบปลอดภัย",
        "เต้น 5 วิ",
        "ให้โต๊ะเลือกอีโมจิ",
        "ขอโทษทั้งโต๊ะ",
        "เปลี่ยนที่นั่ง",
        "งดจับมือถือ 1 รอบ",
      ],
    },
    {
      id: "next-song",
      name: "เลือกเพลงต่อไป",
      items: ["เพลงไทย", "เพลงเก่า", "เพลงตื๊ด", "เพลงเศร้า", "ยุค 90/2000", "เพลงสากล", "ขอเพลงสด", "ให้โต๊ะเลือก"],
    },
    {
      id: "gossip-topic",
      name: "หัวข้อเล่าเรื่อง",
      items: ["คนที่เคยแอบชอบ", "ทริปเก่า", "เรื่องที่ทำงาน", "เรื่องสมัยเรียน", "เดตที่พัง", "ความลับที่เล่าได้", "ชุดคืนนี้", "ประโยคสวนกลับที่ดีที่สุด"],
    },
    {
      id: "order-more",
      name: "สั่งอะไรเพิ่ม",
      items: ["ของทอด", "ยำ", "ปิ้งย่าง", "ข้าว/เส้น", "น้ำแข็ง", "มิกเซอร์", "น้ำอัดลม", "ถามทั้งโต๊ะ"],
    },
    {
      id: "table-job",
      name: "หน้าที่ในโต๊ะ",
      items: ["เรียกพนักงาน", "สั่งอาหาร", "หารบิล", "เลือกเพลง", "ถ่ายรูป", "ดูแผนที่", "เติมน้ำแข็ง", "เลือกร้านต่อไป"],
    },
  ],
};

const pickerStarterPresets: Record<Locale, StarterRandomListPreset[]> = {
  en: [
    {
      id: "friend-truths",
      name: "Truths for friends",
      items: [
        "What was your funniest first impression of someone here?",
        "Who here knows your most embarrassing story?",
        "What old chat would you be scared to open?",
        "What is one harmless secret you can tell tonight?",
        "Who was your most confusing crush?",
        "What is the worst excuse you have used?",
        "What is your most chaotic trip memory?",
        "What is a habit your friends always tease you about?",
        "What song exposes your mood too much?",
        "What is the most dramatic thing you did for love?",
        "Who would you call first after a bad date?",
        "What is one thing you pretend to understand?",
        "What is the silliest thing you have bought at night?",
        "What is the most awkward message you sent?",
        "What rule do you always break a little?",
        "What compliment do you secretly like hearing?",
        "What is your worst karaoke choice?",
        "What story should your family never hear?",
        "What is your weakest excuse for being late?",
        "Who in the table gives the best advice?",
      ],
    },
    {
      id: "bar-dares",
      name: "Bar dares",
      items: [
        "Let the table pick your next photo pose",
        "Say a toast to the person on your right",
        "Speak like a host for one round",
        "Ask the table to rename you for tonight",
        "Let someone choose your profile caption",
        "Sing one chorus quietly at the table",
        "Do a 5-second victory pose",
        "Compliment everyone in one sentence",
        "Tell a story using only 10 words",
        "Swap seats with someone",
        "Hold a serious face for 10 seconds",
        "Let the table choose your emoji",
        "Say one dramatic movie line",
        "Take a harmless group selfie",
        "Explain your outfit like a fashion host",
        "Talk without using 'I' for one round",
        "Use formal language for one round",
        "Give someone a new nickname",
        "Retell tonight like a news anchor",
        "Pick the next table game",
      ],
    },
    {
      id: "never-have-i-ever",
      name: "Never have I ever",
      items: [
        "Never have I ever texted an ex after midnight",
        "Never have I ever pretended not to see a message",
        "Never have I ever lied about being on the way",
        "Never have I ever had a secret crush on a friend",
        "Never have I ever sent a message to the wrong chat",
        "Never have I ever stalked someone's old photos",
        "Never have I ever sung karaoke too seriously",
        "Never have I ever forgotten where I parked",
        "Never have I ever ordered food just because others did",
        "Never have I ever changed plans at the last minute",
        "Never have I ever kept a silly souvenir",
        "Never have I ever practiced a reply before sending it",
        "Never have I ever left a party without saying bye",
        "Never have I ever used work as an excuse",
        "Never have I ever been the last one to leave",
        "Never have I ever regretted a haircut",
        "Never have I ever posted then deleted a story",
        "Never have I ever pretended to like a song",
        "Never have I ever joined a plan for the food",
        "Never have I ever laughed at the wrong time",
      ],
    },
    {
      id: "most-likely-to",
      name: "Most likely to",
      items: [
        "Who is most likely to reply three days later?",
        "Who is most likely to get lost nearby?",
        "Who is most likely to become the group photographer?",
        "Who is most likely to order too much food?",
        "Who is most likely to know everyone at the bar?",
        "Who is most likely to sleep first?",
        "Who is most likely to dance if the song is right?",
        "Who is most likely to give relationship advice?",
        "Who is most likely to forget the plan?",
        "Who is most likely to start the after-party?",
        "Who is most likely to remember every detail?",
        "Who is most likely to arrive late but look good?",
        "Who is most likely to pick the next place?",
        "Who is most likely to become friends with staff?",
        "Who is most likely to say one more round?",
        "Who is most likely to lose their voice tomorrow?",
        "Who is most likely to check the bill carefully?",
        "Who is most likely to make everyone laugh?",
        "Who is most likely to send photos first?",
        "Who is most likely to deny being tired?",
      ],
    },
    {
      id: "forbidden-words",
      name: "Forbidden words",
      items: ["Seriously", "Like", "Actually", "Drunk", "Ex", "Home", "Tomorrow", "Work", "Sleepy", "One more", "Wait", "Bill", "Photo", "Song", "Food"],
    },
    {
      id: "story-prompts",
      name: "Story prompts",
      items: [
        "A night that became a legend",
        "A trip that almost failed",
        "A message you should not have sent",
        "A time you laughed at the wrong moment",
        "A tiny lie that grew too big",
        "A friend who saved the night",
        "A crush story with a bad ending",
        "A food order you still remember",
        "A time you were confidently wrong",
        "A party you left too early",
        "A photo with a backstory",
        "A nickname origin story",
        "A moment you wanted to disappear",
        "A plan that worked by accident",
        "A song tied to a memory",
      ],
    },
    {
      id: "would-you-rather-party",
      name: "Would you rather",
      items: [
        "Would you rather choose the song all night or choose all food?",
        "Would you rather reveal your last search or last photo?",
        "Would you rather be late forever or reply late forever?",
        "Would you rather sing first or dance first?",
        "Would you rather plan every trip or never plan anything?",
        "Would you rather forget names or forget faces?",
        "Would you rather have free snacks or free rides home?",
        "Would you rather hear honest advice or comforting advice?",
        "Would you rather meet your old crush or old teacher here?",
        "Would you rather have no phone or no music tonight?",
        "Would you rather always pick the restaurant or never pick it?",
        "Would you rather be famous in this bar or invisible here?",
        "Would you rather know everyone's secret or have yours known?",
        "Would you rather only drink sweet drinks or bitter drinks?",
        "Would you rather leave early or be the last to leave?",
      ],
    },
    {
      id: "table-votes",
      name: "Table votes",
      items: [
        "Best outfit tonight",
        "Most dramatic storyteller",
        "Most reliable planner",
        "Best laugh",
        "Most likely to vanish from chat",
        "Best song taste",
        "Most suspicious smile",
        "Best advice giver",
        "Most chaotic energy",
        "Most photogenic tonight",
        "Best comeback",
        "Most likely to order again",
        "Most likely to be secretly tired",
        "Best memory keeper",
        "Most changed since we met",
      ],
    },
  ],
  th: [
    {
      id: "friend-truths",
      name: "Truth วงเพื่อน",
      items: [
        "ความประทับใจแรกที่ตลกที่สุดของคนในโต๊ะคืออะไร",
        "ใครในโต๊ะรู้เรื่องหน้าแตกที่สุดของคุณ",
        "แชตเก่าแบบไหนที่ไม่อยากเปิดให้ใครเห็น",
        "ความลับเบา ๆ ที่เล่าได้คืนนี้คืออะไร",
        "เคยแอบชอบใครแบบงงตัวเองที่สุด",
        "ข้ออ้างแย่ที่สุดที่เคยใช้คืออะไร",
        "ความทรงจำทริปที่วุ่นวายที่สุดคืออะไร",
        "นิสัยอะไรที่เพื่อนชอบแซว",
        "เพลงไหนเปิดแล้วเหมือนโป๊ะอารมณ์ตัวเอง",
        "เคยทำอะไรเวอร์ที่สุดเพราะความรัก",
        "ถ้าเดตพังจะโทรหาใครในโต๊ะก่อน",
        "เรื่องอะไรที่ชอบทำเป็นเข้าใจ",
        "ของไร้สาระที่สุดที่เคยซื้อกลางคืนคืออะไร",
        "ข้อความที่ส่งแล้วอึดอัดที่สุดคืออะไร",
        "กฎอะไรที่ชอบแหกนิด ๆ",
        "คำชมแบบไหนที่แอบชอบฟัง",
        "เพลงคาราโอเกะแย่ที่สุดของตัวเองคือเพลงอะไร",
        "เรื่องไหนที่ครอบครัวไม่ควรรู้",
        "ข้ออ้างมาสายที่อ่อนที่สุดคืออะไร",
        "ใครในโต๊ะให้คำปรึกษาดีที่สุด",
      ],
    },
    {
      id: "bar-dares",
      name: "Dare ร้านเหล้า",
      items: [
        "ให้ทั้งโต๊ะเลือกท่าโพสต์รูปให้",
        "กล่าวชนแก้วให้คนขวา",
        "พูดเหมือนพิธีกร 1 รอบ",
        "ให้โต๊ะตั้งชื่อใหม่ให้คืนนี้",
        "ให้เพื่อนเลือกแคปชั่นโปรไฟล์",
        "ร้องท่อนฮุกเบา ๆ ที่โต๊ะ",
        "โพสท่าชนะ 5 วินาที",
        "ชมทุกคนในประโยคเดียว",
        "เล่าเรื่องหนึ่งเรื่องด้วย 10 คำ",
        "สลับที่นั่งกับใครก็ได้",
        "ทำหน้านิ่ง 10 วินาที",
        "ให้โต๊ะเลือกอีโมจิแทนตัวคุณ",
        "พูดประโยคหนังแบบดราม่า",
        "ถ่ายรูปหมู่แบบปลอดภัย",
        "อธิบายชุดตัวเองเหมือนพิธีกรแฟชั่น",
        "ห้ามพูดคำว่า เรา/ฉัน 1 รอบ",
        "พูดสุภาพมาก ๆ 1 รอบ",
        "ตั้งฉายาให้เพื่อน 1 คน",
        "เล่าเหตุการณ์คืนนี้เหมือนผู้ประกาศข่าว",
        "เลือกเกมรอบต่อไป",
      ],
    },
    {
      id: "never-have-i-ever",
      name: "เคยหรือไม่",
      items: [
        "เคยทักแฟนเก่าหลังเที่ยงคืน",
        "เคยทำเป็นไม่เห็นข้อความ",
        "เคยโกหกว่าใกล้ถึงแล้ว",
        "เคยแอบชอบเพื่อน",
        "เคยส่งข้อความผิดแชต",
        "เคยไล่ดูรูปเก่าของใครบางคน",
        "เคยร้องคาราโอเกะจริงจังเกินไป",
        "เคยลืมว่าจอดรถไว้ไหน",
        "เคยสั่งอาหารตามคนอื่นเพราะคิดไม่ออก",
        "เคยเปลี่ยนแผนกะทันหัน",
        "เคยเก็บของที่ระลึกไร้สาระ",
        "เคยซ้อมตอบแชตก่อนส่ง",
        "เคยออกจากงานโดยไม่บอกลา",
        "เคยอ้างงานเพื่อไม่ไปไหน",
        "เคยเป็นคนสุดท้ายที่ออกจากร้าน",
        "เคยเสียใจกับทรงผมตัวเอง",
        "เคยลงสตอรี่แล้วลบ",
        "เคยทำเป็นชอบเพลงที่ไม่ชอบ",
        "เคยไปเพราะอยากกินอาหาร",
        "เคยหัวเราะผิดจังหวะ",
      ],
    },
    {
      id: "most-likely-to",
      name: "ใครน่าจะที่สุด",
      items: [
        "ใครน่าจะตอบแชตช้าไปสามวัน",
        "ใครน่าจะหลงทางแถวนี้",
        "ใครน่าจะเป็นช่างภาพประจำกลุ่ม",
        "ใครน่าจะสั่งอาหารเกินพอดี",
        "ใครน่าจะรู้จักคนทั้งร้าน",
        "ใครน่าจะหลับก่อน",
        "ใครน่าจะเต้นถ้าเพลงใช่",
        "ใครน่าจะให้คำปรึกษาความรัก",
        "ใครน่าจะลืมแผนที่นัดไว้",
        "ใครน่าจะเริ่มไปร้านต่อ",
        "ใครน่าจะจำรายละเอียดได้หมด",
        "ใครน่าจะมาสายแต่แต่งตัวดี",
        "ใครน่าจะเลือกร้านถัดไป",
        "ใครน่าจะสนิทกับพนักงาน",
        "ใครน่าจะพูดว่าอีกรอบเดียว",
        "ใครน่าจะเสียงหายพรุ่งนี้",
        "ใครน่าจะตรวจบิลละเอียด",
        "ใครน่าจะทำให้ทุกคนหัวเราะ",
        "ใครน่าจะส่งรูปให้ก่อน",
        "ใครน่าจะปฏิเสธว่าง่วง",
      ],
    },
    {
      id: "forbidden-words",
      name: "คำต้องห้าม",
      items: ["เอาจริง", "แบบว่า", "จริงดิ", "เมา", "แฟนเก่า", "กลับบ้าน", "พรุ่งนี้", "งาน", "ง่วง", "อีกรอบ", "เดี๋ยว", "บิล", "รูป", "เพลง", "อาหาร"],
    },
    {
      id: "story-prompts",
      name: "หัวข้อเล่าเรื่อง",
      items: [
        "คืนที่กลายเป็นตำนาน",
        "ทริปที่เกือบพัง",
        "ข้อความที่ไม่น่าส่ง",
        "ตอนที่หัวเราะผิดเวลา",
        "คำโกหกเล็ก ๆ ที่บานปลาย",
        "เพื่อนที่ช่วยชีวิตคืนนั้น",
        "เรื่องแอบชอบที่จบไม่สวย",
        "ออเดอร์อาหารที่ยังจำได้",
        "ตอนที่มั่นใจแต่ผิดเต็ม ๆ",
        "ปาร์ตี้ที่กลับเร็วเกินไป",
        "รูปหนึ่งรูปที่มีเรื่องเบื้องหลัง",
        "ที่มาของฉายา",
        "โมเมนต์ที่อยากหายตัว",
        "แผนที่สำเร็จแบบฟลุก",
        "เพลงที่ผูกกับความทรงจำ",
      ],
    },
    {
      id: "would-you-rather-party",
      name: "เลือกแบบไหนดี",
      items: [
        "เลือกเพลงทั้งคืน หรือเลือกอาหารทั้งหมด",
        "เปิดประวัติค้นหาล่าสุด หรือเปิดรูปล่าสุด",
        "มาสายตลอด หรือ ตอบแชตช้าตลอด",
        "ร้องเพลงก่อน หรือ เต้นก่อน",
        "วางแผนทุกทริป หรือ ไม่วางแผนอะไรเลย",
        "จำชื่อคนไม่ได้ หรือ จำหน้าคนไม่ได้",
        "ของกินฟรี หรือ รถกลับบ้านฟรี",
        "คำแนะนำตรง ๆ หรือ คำปลอบใจ",
        "เจอคนที่เคยแอบชอบ หรือ เจอครูเก่าที่นี่",
        "คืนนี้ไม่มีมือถือ หรือ ไม่มีเพลง",
        "เลือกร้านอาหารตลอด หรือ ห้ามเลือกร้านเลย",
        "ดังทั้งร้าน หรือ ไม่มีใครเห็น",
        "รู้ความลับทุกคน หรือ ทุกคนรู้ความลับเรา",
        "ดื่มได้แต่หวาน หรือ ดื่มได้แต่ขม",
        "กลับเร็ว หรือ อยู่เป็นคนสุดท้าย",
      ],
    },
    {
      id: "table-votes",
      name: "โหวตเพื่อนในวง",
      items: [
        "แต่งตัวดีที่สุดคืนนี้",
        "เล่าเรื่องดราม่าที่สุด",
        "วางแผนเก่งที่สุด",
        "หัวเราะอร่อยที่สุด",
        "หายจากแชตเก่งที่สุด",
        "รสนิยมเพลงดีที่สุด",
        "ยิ้มน่าสงสัยที่สุด",
        "ให้คำปรึกษาดีที่สุด",
        "พลังวุ่นวายที่สุด",
        "ขึ้นกล้องที่สุดคืนนี้",
        "สวนกลับเก่งที่สุด",
        "น่าจะสั่งเพิ่มที่สุด",
        "น่าจะแอบง่วงที่สุด",
        "จำเรื่องเก่งที่สุด",
        "เปลี่ยนไปมากที่สุดตั้งแต่รู้จักกัน",
      ],
    },
  ],
};

export function getWheelStarterPresets(locale: Locale) {
  return wheelStarterPresets[locale].map(toRandomListStarterPreset);
}

export function getPickerStarterPresets(locale: Locale) {
  return pickerStarterPresets[locale].map(toRandomListStarterPreset);
}

function toRandomListStarterPreset(preset: StarterRandomListPreset) {
  return {
    id: `starter-${preset.id}`,
    name: preset.name,
    items: createRandomListItems(preset.id, preset.items),
  };
}

function createRandomListItems(presetId: string, labels: string[]) {
  return sanitizeRandomListItems(
    labels.map((label, index): RandomListItem => ({
      id: `${presetId}-${index + 1}`,
      label,
      color: palette[index % palette.length] ?? defaultRandomListColor,
      weight: 1,
      enabled: true,
    })),
  );
}
